# Generated by Django 4.0 on 2022-02-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('nft_management', '0001_initial'),
        ('wallet_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.FloatField(verbose_name='bidding_price')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_nft', to='nft_management.nft')),
                ('offer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_biding', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='NftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.FloatField()),
                ('sold_date', models.DateTimeField(auto_now_add=True)),
                ('service_fee', models.FloatField(default=0.0)),
                ('is_removed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_buyer', to='accounts.user')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_transaction', to='nft_management.nft')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_seller', to='accounts.user')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='wallet_management.wallet')),
            ],
            options={
                'unique_together': {('buyer', 'seller')},
            },
        ),
    ]
