# Generated by Django 4.0.2 on 2022-02-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royalty', models.IntegerField()),
                ('platform_share', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('mailgun_domain', models.URLField()),
                ('mailgun_Api_Key', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord', models.URLField()),
                ('twitter', models.URLField()),
                ('youTube', models.URLField()),
                ('instagram', models.URLField()),
                ('medium', models.URLField()),
                ('telegram', models.URLField()),
                ('reddit', models.URLField()),
                ('github', models.URLField()),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
